<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anthology.Contracts\Anthology.Contracts.csproj" />
    <ProjectReference Include="..\Anthology.Update.Core\Anthology.Update.Core.csproj" />
  </ItemGroup>
</Project>
